<?xml version="1.0"?>
<package format="2">
  <name>bevdet_vendor</name>
  <version>0.0.0</version>
  <description>The bevdet tensorrt package</description>

  <maintainer email="cynthia.liu@autocore.ai">cyn-liu</maintainer>
  <maintainer email="dongyixiao2001@163.com">Dong Yixiao</maintainer>

  <license>LCH1238</license>

  <buildtool_depend>ament_cmake_auto</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_components</depend>
  <depend>message_filters</depend>
  <depend>sensor_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>visualization_msgs</depend>

  <!-- TODO: replace yaml with ros params -->
  <depend>yaml-cpp</depend>

  <depend>cv_bridge</depend> <!-- Temporarily Use -->
  <depend>pcl_conversions</depend>
  <depend>pcl_ros</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
